import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Navbar } from "flowbite-react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const steps = {
    cover: {
      content: <p aria-label="cover">cover</p>,
    },
    main: {
      content: <p aria-label="main">isi</p>,
    },
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <div className="container bg-red-200">
        <div className=" bg-green-200">
          <h1 className="text-3xl font-bold font-kurale">Hello Jenni`!</h1>
          <h1 className="text-3xl font-bold font-noto-sans-symbols">
            Hello Jenni`!
          </h1>
          <h1 className="text-3xl font-bold font-passions-conflict">
            Hello Jenni`!
          </h1>
          <h1 className="text-3xl font-bold font-rozha-one">Hello Jenni`!</h1>
          <h1 className="text-3xl font-bold font-kapakana">Hello Jenni`!</h1>
          <h1 className="text-3xl font-bold font-bad-script">Hello Jenni`!</h1>
        </div>
      </div>
    </>
  );
}
